version: "3.8"
services:
    redis:
        image: 'redis'
        container_name: collector-app-redis
        networks:
            - collector-app-network

    mysql:
        image: mysql:latest
        container_name: collector-app-mysql
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "collector_db"
        volumes:
            - ./database/mysql/:/var/lib/mysql
        ports:
            - 3310:3306
        networks:
            - collector-app-network

    django:
        build: ./src
        container_name: collector-app-django
        volumes:
            - ./src/:/usr/src/app/
        networks:
            - collector-app-network
        env_file:
            - ./.env
        depends_on:
            - mysql
            - redis
        image: collector-app-django
        restart: unless-stopped

    worker:
        image: collector-app-django
        container_name: collector-app-worker
        volumes:
            - ./src/:/usr/src/app/
        networks:
            - collector-app-network
        env_file:
            - ./.env
        environment:
            WORKER: 1
        depends_on:
            - django
        restart: unless-stopped

    nginx:
        build: ./nginx
        container_name: collector-app-nginx
        volumes:
            - ./src/staticfiles/:/usr/src/app/staticfiles/
        networks:
            - collector-app-network
        ports:
            - 8000:80
        depends_on:
            - django
        image: collector-app-nginx
        restart: unless-stopped

networks:
    collector-app-network:
