# Generated by Django 4.0.2 on 2022-02-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rtl',
            field=models.BooleanField(default=True),
        ),
    ]
