# Generated by Django 4.0.2 on 2022-02-21 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_alter_post_author_describtion_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
